In [2]:
from pytrends.request import TrendReq
import pandas
import datetime

In [3]:
kw_list = ['buy bitcoin','btc usd']

pytrends = TrendReq(hl='en - US')

In [4]:
pytrends.build_payload(kw_list, cat=0, timeframe='2017-01-18 2017-5-18', geo='', gprop='')

In [5]:
df = pytrends.interest_over_time()

In [50]:
end_date = datetime.datetime.now().date()
start_date = end_date - datetime.timedelta(days=180)

In [53]:
str(start_date)

'2018-04-21'

In [46]:
date.now()

NameError: name 'date' is not defined

In [35]:
start_date - datetime.timedelta(days=1)

datetime.date(2012, 9, 15)

In [37]:
start_date - datetime.timedelta(days=180)

datetime.date(2012, 3, 20)

In [6]:
df

            buy bitcoin  btc usd  isPartial
date
2017-01-18           20       52      False
2017-01-19           19       39      False
2017-01-20           16       39      False
2017-01-21           15       37      False
2017-01-22           16       36      False
2017-01-23           18       40      False
2017-01-24           16       42      False
2017-01-25           13       34      False
2017-01-26           17       43      False
2017-01-27           19       35      False
2017-01-28           19       32      False
2017-01-29           14       30      False
2017-01-30           21       32      False
2017-01-31           16       40      False
2017-02-01           20       39      False
2017-02-02           15       48      False
2017-02-03           15       52      False
2017-02-04           17       44      False
2017-02-05           16       40      False
2017-02-06           15       45      False
2017-02-07           20       45      False
2017-02-08           18       43      False
2017-02-09           17       51      False
2017-02-10           17       44      False
2017-02-11           16       44      False
2017-02-12           18       39      False
2017-02-13           13       37      False
2017-02-14           13       32      False
2017-02-15           15       37      False
2017-02-16           16       37      False
...                 ...      ...        ...
2017-04-19           19       44      False
2017-04-20           19       47      False
2017-04-21           17       52      False
2017-04-22           18       40      False
2017-04-23           21       45      False
2017-04-24           18       44      False
2017-04-25           21       54      False
2017-04-26           19       53      False
2017-04-27           16       55      False
2017-04-28           20       60      False
2017-04-29           22       49      False
2017-04-30           28       54      False
2017-05-01           23       66      False
2017-05-02           23       66      False
2017-05-03           28       69      False
2017-05-04           36       88      False
2017-05-05           32       84      False
2017-05-06           31       64      False
2017-05-07           27       69      False
2017-05-08           28       79      False
2017-05-09           36      100      False
2017-05-10           35       89      False
2017-05-11           36       99      False
2017-05-12           43       95      False
2017-05-13           38       88      False
2017-05-14           34       83      False
2017-05-15           46       88      False
2017-05-16           39       87      False
2017-05-17           38       85      False
2017-05-18           35       80      False

[121 rows x 3 columns]

In [8]:
for index, row in df.iterrows():
    print(index)

2017-01-18 00:00:00
2017-01-19 00:00:00
2017-01-20 00:00:00
2017-01-21 00:00:00
2017-01-22 00:00:00
2017-01-23 00:00:00
2017-01-24 00:00:00
2017-01-25 00:00:00
2017-01-26 00:00:00
2017-01-27 00:00:00
2017-01-28 00:00:00
2017-01-29 00:00:00
2017-01-30 00:00:00
2017-01-31 00:00:00
2017-02-01 00:00:00
2017-02-02 00:00:00
2017-02-03 00:00:00
2017-02-04 00:00:00
2017-02-05 00:00:00
2017-02-06 00:00:00
2017-02-07 00:00:00
2017-02-08 00:00:00
2017-02-09 00:00:00
2017-02-10 00:00:00
2017-02-11 00:00:00
2017-02-12 00:00:00
2017-02-13 00:00:00
2017-02-14 00:00:00
2017-02-15 00:00:00
2017-02-16 00:00:00
2017-02-17 00:00:00
2017-02-18 00:00:00
2017-02-19 00:00:00
2017-02-20 00:00:00
2017-02-21 00:00:00
2017-02-22 00:00:00
2017-02-23 00:00:00
2017-02-24 00:00:00
2017-02-25 00:00:00
2017-02-26 00:00:00
2017-02-27 00:00:00
2017-02-28 00:00:00
2017-03-01 00:00:00
2017-03-02 00:00:00
2017-03-03 00:00:00
2017-03-04 00:00:00
2017-03-05 00:00:00
2017-03-06 00:00:00
2017-03-07 00:00:00
2017-03-08 00:00:00
2017-03-09 00:00:00
2017-03-10 00:00:00
2017-03-11 00:00:00
2017-03-12 00:00:00
2017-03-13 00:00:00
2017-03-14 00:00:00
2017-03-15 00:00:00
2017-03-16 00:00:00
2017-03-17 00:00:00
2017-03-18 00:00:00
2017-03-19 00:00:00
2017-03-20 00:00:00
2017-03-21 00:00:00
2017-03-22 00:00:00
2017-03-23 00:00:00
2017-03-24 00:00:00
2017-03-25 00:00:00
2017-03-26 00:00:00
2017-03-27 00:00:00
2017-03-28 00:00:00
2017-03-29 00:00:00
2017-03-30 00:00:00
2017-03-31 00:00:00
2017-04-01 00:00:00
2017-04-02 00:00:00
2017-04-03 00:00:00
2017-04-04 00:00:00
2017-04-05 00:00:00
2017-04-06 00:00:00
2017-04-07 00:00:00
2017-04-08 00:00:00
2017-04-09 00:00:00
2017-04-10 00:00:00
2017-04-11 00:00:00
2017-04-12 00:00:00
2017-04-13 00:00:00
2017-04-14 00:00:00
2017-04-15 00:00:00
2017-04-16 00:00:00
2017-04-17 00:00:00
2017-04-18 00:00:00
2017-04-19 00:00:00
2017-04-20 00:00:00
2017-04-21 00:00:00
2017-04-22 00:00:00
2017-04-23 00:00:00
2017-04-24 00:00:00
2017-04-25 00:00:00
2017-04-26 00:00:00
2017-04-27 00:00:00
2017-04-28 00:00:00
2017-04-29 00:00:00
2017-04-30 00:00:00
2017-05-01 00:00:00
2017-05-02 00:00:00
2017-05-03 00:00:00
2017-05-04 00:00:00
2017-05-05 00:00:00
2017-05-06 00:00:00
2017-05-07 00:00:00
2017-05-08 00:00:00
2017-05-09 00:00:00
2017-05-10 00:00:00
2017-05-11 00:00:00
2017-05-12 00:00:00
2017-05-13 00:00:00
2017-05-14 00:00:00
2017-05-15 00:00:00
2017-05-16 00:00:00
2017-05-17 00:00:00
2017-05-18 00:00:00